# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_1',
            new_name='price',
        ),
    ]
