# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Full Name')),
                ('address', models.CharField(blank=True, max_length=240, null=True)),
                ('address_2', models.CharField(blank=True, max_length=240, null=True)),
                ('Biography', models.TextField()),
            ],
        ),
    ]
