# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Full Name')),
                ('address', models.CharField(blank=True, max_length=240, null=True)),
                ('address_2', models.CharField(blank=True, max_length=240, null=True)),
                ('member_since', models.DateField(auto_now_add=True, verbose_name='signup date')),
                ('phone_number', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('biography', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user name')),
            ],
        ),
    ]
