# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_profile_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_since',
            field=models.DateField(auto_now_add=True, verbose_name='signup date'),
        ),
    ]
