# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20170531_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=1, max_length=120, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
