# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('make', models.CharField(blank=True, max_length=120, null=True, verbose_name='model')),
                ('age', models.CharField(blank=True, help_text='Ignore if not applicable', max_length=120, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
