# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170529_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Default Value'),
            preserve_default=False,
        ),
    ]
