# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170530_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100, verbose_name='market_price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100, verbose_name='my_price'),
        ),
    ]
