# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170530_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100, verbose_name='Market price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=100, verbose_name='My price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
