# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_myproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProduct',
            new_name='MyProducts',
        ),
        migrations.AlterModelOptions(
            name='myproducts',
            options={'verbose_name': 'My products', 'verbose_name_plural': 'My products'},
        ),
        migrations.RenameField(
            model_name='myproducts',
            old_name='product',
            new_name='products',
        ),
    ]
