# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_thumbnail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_2_active',
            field=models.BooleanField(default=False),
        ),
    ]
