# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('products', '0019_product_price_2_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sellers.SellerAccount'),
            preserve_default=False,
        ),
    ]
